version: '3.8'

services:
  vllm-server:
    image: slabstech/dwani-vllm
    runtime: nvidia
    environment:
      - HF_TOKEN=my-nsma-is-what
    ports:
      - "9000:9000"
    command: >
      serve google/gemma-3-4b-it
      --served-model-name gemma3
      --host 0.0.0.0
      --port 9000
      --gpu-memory-utilization 0.9
      --tensor-parallel-size 1
      --max-model-len 16384
      --dtype bfloat16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
